#!/usr/bin/env bash
# This script creates a PID file, displays messages indefinitely, and handles signals

# Create a PID file
echo $$ > /var/run/myscript.pid

handle_sigterm() {
    echo "I hate the kill command"
}

handle_sigint() {
    echo "Y U no love me?!"
}

handle_sigquit() {
    rm /var/run/myscript.pid
    exit 1
}

# Set up signal handlers
trap 'handle_sigterm' SIGTERM
trap 'handle_sigint' SIGINT
trap 'handle_sigquit' SIGQUIT

# Display message indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 1
done
