#!/usr/bin/env bash
# This script reads the /etc/passwd file and displays the username, user id, and home directory for each user

while IFS=: read -r username _ userid _ _ homedir _
do
    echo "$username:$userid:$homedir"
done < /etc/passwd
